services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: irango-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--max-old-space-size=2048
    env_file:
      - .env.local
    command: npm run dev
